import type { Metadata } from "next";
import "./globals.css";
import ThemeContextProvider from "@/context/ThemeContextProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fn" dir="rtl">
      <body>
        <ThemeContextProvider>
          <CssBaseline/>
          <Header />
          {children}
          <Footer />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
