import type { Metadata } from "next";
import "./globals.css";
import ThemeContextProvider from "@/context/ThemeContextProvider";
import { CssBaseline } from "@mui/material";
import QueryContextProvider from "@/context/QueryContextProvider";
import LayoutHandler from "@/components/layout";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "کتاب ویدا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fn" dir="rtl">
      <body>
        <QueryContextProvider>
          <ThemeContextProvider>
            <CssBaseline />
            <Suspense fallback={<Loading />}>
              <LayoutHandler>{children}</LayoutHandler>
            </Suspense>
          </ThemeContextProvider>
        </QueryContextProvider>
      </body>
    </html>
  );
}
