import type { Metadata } from "next";
import "./globals.css";
import ThemeContextProvider from "@/context/ThemeContextProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CssBaseline } from "@mui/material";
import QueryContextProvider from "@/context/QueryContextProvider";
import { usePathname } from "next/navigation";
import LayoutHandler from "@/components/layout";

export const metadata: Metadata = {
  title: "کتاب ویدا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fn" dir="rtl">
      <body>
        <QueryContextProvider>
          <ThemeContextProvider>
            <CssBaseline />
            <LayoutHandler>{children}</LayoutHandler>
          </ThemeContextProvider>
        </QueryContextProvider>
      </body>
    </html>
  );
}
